### PR TITLE
feat: allow serialization of unit structs

### LINKED ISSUE #50: Unit structs
Currently, attempting to serialize a unit struct returns an error: "top-level serializer supports only maps and structs".

Since serialization of `Option::None` is allowed, I would expect the same behavior for unit structs, ie returning empty pairs.

Would that change be acceptable ?

### PR DESCRIPTION
**Pull request by fdehau**
fix #50

### CODE REVIEW

**Comment by nox** [comment]
What is the purpose of that change? Why should the input be ignored when trying to deserialise a unit struct? Why deserialise to a unit struct in the first place? `Option<T>` is supported because you could want to deserialise `Some(actual_stuff)`, whereas I don't see a use case for unit structs there.

**Comment by nox** [comment]
Err, didn't notice it is for serialisation.

**Comment by nox** [comment]
Why would you want to serialise an unit struct into nothing?

**Comment by fdehau** [comment]
Sorry for the inactivity on this issue. For a bit of context for this issue, I was using this crate through reqwest for a prototype api client. My approach was to have something like:

```rust
trait Request: Deserialize {
   type Response;
}
```
with a bunch of methods on it. In some case a GET request would not have any parameters and thus be represented by unit structs. I found it a bit surprising that this would not work as this crate would refuse to serialize the unit structs.

This is possibly a problem with my original design but since `Option` is already serialized into nothing and from my experience unit structs and `None` both gives null in `serde_json`, I was assuming that it was a reasonable change.

**Comment by nox** [comment]
I see. I'll merge it if you rebase.

**Comment by fdehau** [comment]
Thanks. It's done.

**Pull request merged**
