### PR TITLE
Fix struct newtype deserialization (and add tests)

### LINKED ISSUE #41: Can't deserialize newtype structs
This issue was previously reported here : #14. 

I still see this problem. I added a test function to `test_deserialize.rs`. Perhaps i'm writing this incorrectly, see the function below, followed by the result of running the test.

```
#[test]
fn deserialize_newtype() {
    #[derive(Serialize, Deserialize, Debug, PartialEq, Eq)]
    struct TestNewType(u32);
    let result = TestNewType(42);

    assert_eq!(serde_urlencoded::from_str::<TestNewType>("testnewtype=42"), Ok(result));
}
```

The result is: 

```
running 7 tests
test deserialize_bytes ... ok
test deserialize_option ... ok
test deserialize_reader ... ok
test deserialize_str ... ok
test deserialize_unit ... ok
test deserialize_unit_enum ... ok
test deserialize_newtype ... FAILED

failures:

---- deserialize_newtype stdout ----
thread 'deserialize_newtype' panicked at 'assertion failed: `(left == right)`
  left: `Err(Error { err: "invalid type: map, expected tuple struct TestNewType" })`,
 right: `Ok(TestNewType(42))`', tests/test_deserialize.rs:70:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    deserialize_newtype
```

### PR DESCRIPTION
**Pull request by samsieber**
Fixes #41

I only had to fix the deserializer - the serialization already works. So now they work the same way - you can serialize something and then deserialize it losslessly. 

I also added tests for serialization and deserialization. Let me know if there's anything you'd like changed.

### CODE REVIEW

**Comment by nox** [comment]
Nice. Could you bump the version to 0.5.4 while at it?

**Comment by samsieber** [comment]
Sure - version bumped

**Comment by nox** [comment]
bors r+

Feel free to ping me if I forget to publish the new version once this lands.

**Comment by samsieber** [comment]
@nox ping! I actually have no idea how long it takes for you to cut a release, so I'll ping you again in a day or two if I don't see it.

**Pull request merged**
