### PR TITLE
Add license 1

### PR DESCRIPTION
**Pull request by Trard**

### CODE REVIEW

**Comment by Trard** [comment]
missclick

**Comment by nox** [comment]
Note that `serde_qs` is a crate that exists and supports sequences.

**Comment by Trard** [comment]
I know, but i need query in comma separated format.

**Comment by nox** [comment]
You don't really need to fork serde_urlencoded for that, you can use `serialize_with` and `deserialize_with` https://serde.rs/field-attrs.html#serialize_with

**Pull request closed without merging**
