### PR TITLE
2018 edition

### PR DESCRIPTION
**Pull request by Gisleburt**
This was generated with `cargo fix --edition` so should resolve the comments on #56

### CODE REVIEW

**Comment by nox** [comment]
Duplicate of #56 which I'm not merging because that needs a breaking change.

**Comment by Gisleburt** [comment]
Is there anything I can do to help?

#56 has been stale for nine months, and I was hoping to follow this PR with some documentation if possible.

Is it possible to write the documentation in a different edition?

**Comment by nox** [comment]
I completely forgot about the comment I made on the other PR and I forgot back then to precise that I would not merge it as long as I don't need to land any other breaking change, because I don't want to increase the minimum Rust version until there is a need to.

**Comment by Gisleburt** [comment]
Thats a really good point that I didn't think about.

I'll try see if I can write some docs using 2015, though I was having a bit of trouble with the macros, I'm sure I can work it out.

**Comment by nickelc** [comment]
MSRV is 1.36.0 because of `form_urlencoded -> percent-encoding v2.1.0`

**Comment by nox** [comment]
I'll merge it if it gets rebased.

**Comment by jplatte** [comment]
Superseded by #81.

**Pull request closed without merging**
