### PR TITLE
Implement serialization/deserialization of nested sequences

### PR DESCRIPTION
**Pull request by andy128k**

### CODE REVIEW

**Comment by nox** [comment]
I don't understand what that does, please explain.

**Comment by andy128k** [comment]
@nox It allows to serialize/deserialize sequences. HTML form with `<select multiple>` is an example of such things.

Working on this I realized that keys and values should be processed differently. So, I copied implementations.`ValueSerializer` replaces `PartSerializer<ValueSink>`. 

Deserializer is also copied. Now it could process pairs `(Part<'de>, Part<'de>)` for sequences in root and `(Part<'de>, Value<'de>)` for all other cases.

**Comment by nox** [comment]
I see. This is kinda out of scope for this crate, given there is no way to
do it correctly without introducing intermediate allocations for when the
same keys are not interspersed by other ones.

Le mar. 9 oct. 2018 à 14:29, Andrey Kutejko <notifications@github.com> a
écrit :

**Comment by andy128k** [comment]
Could you elaborate please? How deserializing of HTML forms with multi-selects or checkboxes fells out of scope of the crate? And what's wrong with allocations? BTW, intermediate allocations are still required even if keys are not interspersed.

**Comment by nox** [comment]
> Could you elaborate please? How deserializing of HTML forms with multi-selects or checkboxes fells out of scope of the crate?

Because I decided it was out of scope for this crate to do things that require intermediate allocations. You can use `serde_qs` if you want fancier features.

> BTW, intermediate allocations are still required even if keys are not interspersed.

They shouldn't be required if the keys are not interspersed given you can use the sequence deserialiser on the fly in that case.

**Pull request closed without merging**
